/**
 * Run checkpoint store.
 *
 * Persists every agent run's progress to `data/checkpoints/<runId>.json` so
 * that:
 *  1. A crashed/restarted process can be told "your last 14 runs were
 *     `running` when you went down — they are now `interrupted`".
 *  2. An external supervisor can `GET /runs` to see live + historical state.
 *  3. A user can `POST /runs/:id/resume` to retry an interrupted run with
 *     the prior partial output replayed as context.
 *
 * The checkpoint shape is intentionally narrow — we record what's needed to
 * REASON about a run, not the full LangGraph state. Mid-graph resumption is
 * not attempted because our streamEvents loop is not a snapshottable state
 * machine. The trade-off: a resumed run re-does the work, but with the
 * prior partial answer as a hint, which usually short-circuits exploration.
 *
 * Failures here MUST never break a run, so every IO call is best-effort.
 */

import * as fs from "fs";
import * as path from "path";

import { ChatHistoryMessage } from "./types";
import { RunContext } from "./run-context";

export type CheckpointStatus =
  | "running"
  | "completed"
  | "failed"
  | "interrupted"
  | "cancelled";

export interface RunCheckpoint {
  runId: string;
  sessionId: string;
  prompt: string;
  history: ChatHistoryMessage[];
  /** Accumulated assistant text — saved incrementally during streaming. */
  partialAnswer: string;
  /** Tool calls observed so far (name + ms + isError). */
  toolEvents: { name: string; durationMs?: number; isError: boolean }[];
  runCtx: {
    complexity: string;
    toolCallCount: number;
    searchCallCount: number;
    browseCallCount: number;
    costScore: number;
    costCeiling: number;
    budgetMaxToolCalls: number;
  };
  startedAt: number;
  updatedAt: number;
  completedAt?: number;
  status: CheckpointStatus;
  error?: string;
}

const ROOT = path.resolve(__dirname, "../..");
const CHECKPOINT_DIR = path.join(ROOT, "data", "checkpoints");
/** Hard cap on how many runs we keep per scan. Prunes oldest first. */
const MAX_KEPT = (() => {
  const parsed = Number(process.env.CHECKPOINT_MAX_KEPT);
  return Number.isFinite(parsed) ? Math.max(50, Math.min(5000, Math.floor(parsed))) : 500;
})();
/** Drop completed/failed runs older than this many days. 0 disables. */
const TTL_DAYS = (() => {
  const parsed = Number(process.env.CHECKPOINT_TTL_DAYS);
  return Number.isFinite(parsed) ? Math.max(0, Math.min(365, Math.floor(parsed))) : 14;
})();

function ensureDir(): void {
  try {
    fs.mkdirSync(CHECKPOINT_DIR, { recursive: true });
  } catch (err: any) {
    console.warn(`[checkpoint] mkdir failed: ${err?.message ?? err}`);
  }
}

function fileFor(runId: string): string {
  // runId is generated by us (TrajectoryLogger) so the slug is safe.
  return path.join(CHECKPOINT_DIR, `${runId}.json`);
}

/** Snapshot the dynamic parts of RunContext into a JSON-friendly shape. */
export function snapshotRunCtx(runCtx: RunContext): RunCheckpoint["runCtx"] {
  return {
    complexity: runCtx.complexity,
    toolCallCount: runCtx.toolCallCount,
    searchCallCount: runCtx.searchCallCount,
    browseCallCount: runCtx.browseCallCount,
    costScore: runCtx.costScore,
    costCeiling: runCtx.costCeiling,
    budgetMaxToolCalls: runCtx.budget.maxToolCalls,
  };
}

export class CheckpointStore {
  /** Atomic-ish write — write to .tmp then rename so partial files never load. */
  save(checkpoint: RunCheckpoint): void {
    ensureDir();
    const finalPath = fileFor(checkpoint.runId);
    const tmpPath = `${finalPath}.tmp`;
    try {
      fs.writeFileSync(tmpPath, JSON.stringify(checkpoint, null, 2), "utf8");
      fs.renameSync(tmpPath, finalPath);
    } catch (err: any) {
      console.warn(`[checkpoint] save failed for ${checkpoint.runId}: ${err?.message ?? err}`);
    }
  }

  load(runId: string): RunCheckpoint | null {
    try {
      const raw = fs.readFileSync(fileFor(runId), "utf8");
      const parsed = JSON.parse(raw);
      if (parsed && typeof parsed === "object" && parsed.runId === runId) {
        return parsed as RunCheckpoint;
      }
      return null;
    } catch {
      return null;
    }
  }

  /** List all runs, newest first. */
  list(): RunCheckpoint[] {
    ensureDir();
    let names: string[] = [];
    try {
      names = fs.readdirSync(CHECKPOINT_DIR);
    } catch {
      return [];
    }
    const records: RunCheckpoint[] = [];
    for (const name of names) {
      if (!name.endsWith(".json")) continue;
      const runId = name.slice(0, -5);
      const record = this.load(runId);
      if (record) records.push(record);
    }
    records.sort((a, b) => b.startedAt - a.startedAt);
    return records;
  }

  delete(runId: string): boolean {
    try {
      fs.unlinkSync(fileFor(runId));
      return true;
    } catch {
      return false;
    }
  }

  /**
   * Convert any `running` checkpoint to `interrupted` — called once at boot
   * because a `running` record on a fresh process means the previous
   * process died mid-run.
   */
  markStaleAsInterrupted(): number {
    let count = 0;
    for (const record of this.list()) {
      if (record.status === "running") {
        record.status = "interrupted";
        record.error = "Process restart detected — original run was killed before completion.";
        record.updatedAt = Date.now();
        this.save(record);
        count += 1;
      }
    }
    return count;
  }

  /**
   * Apply size + age limits. Keeps newest `MAX_KEPT`; drops completed/failed
   * older than `TTL_DAYS`. Interrupted runs are always kept until a user
   * resumes or deletes them so they don't silently disappear.
   */
  prune(): { removed: number } {
    const records = this.list();
    let removed = 0;
    const now = Date.now();
    const ttlMs = TTL_DAYS > 0 ? TTL_DAYS * 86_400_000 : 0;

    for (let i = 0; i < records.length; i += 1) {
      const record = records[i];
      const overflow = i >= MAX_KEPT;
      const expired =
        ttlMs > 0 &&
        (record.status === "completed" || record.status === "failed" || record.status === "cancelled") &&
        now - (record.completedAt ?? record.updatedAt) > ttlMs;
      if (overflow || expired) {
        if (this.delete(record.runId)) removed += 1;
      }
    }
    return { removed };
  }
}

export const checkpointStore = new CheckpointStore();
